# /etc/nginx/sites-available/octoprint
# Raspberry Pi — RCI3D Project
# IP Pi: 10.142.162.197

server {
    listen 80;
    server_name _;

    location / {
        proxy_pass          http://127.0.0.1:5000;
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection "upgrade";
        proxy_read_timeout  90;

        # CORS — autoriser Firebase hosting
        add_header 'Access-Control-Allow-Origin'  'https://rci3d-app-2026.web.app' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'X-Api-Key, Content-Type, Authorization' always;
        add_header 'Access-Control-Max-Age'       '3600' always;

        # Répondre aux preflight OPTIONS immédiatement
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin'  'https://rci3d-app-2026.web.app';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'X-Api-Key, Content-Type, Authorization';
            add_header 'Content-Length' 0;
            return 204;
        }
    }
}
